### PR TITLE
use latest ABCI++ version of core and add the new methods to baseapp

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

v0.44.x based cosmos-sdk branch that is modified to use celestia-core master and the two new methods from ABCI++

### CODE REVIEW

**Review by SweeXordious — APPROVED** [review]

**Comment by evan-forbes** [comment]
the remaining failing test is expected, as we don't yet support returning proofs for large transactions
```
TestIntegrationTestSuite/TestCLIQueryTxsCmdByEvents/fee_event_happy_case (0.00s)
            suite.go:483: 
                	Error Trace:	suite.go:483
                	            				suite.go:77
                	Error:      	Received unexpected error:
                	            	transaction spanned more than two shares, this is not yet supported
```

tbc, the transaction is still being committed to and applies the appropriate state changes, we just can't yet prove that it was committed in a block. We have an issue for this in [#621](https://github.com/celestiaorg/celestia-core/issues/621)

**Comment by adlerjohn** [comment]
What's the status of this?

**Comment by evan-forbes** [comment]
> What's the status of this?

its currently blocked by [#631](https://github.com/celestiaorg/celestia-core/pull/631), but other than that it's good to go

**Comment by adlerjohn** [comment]
Can we convert to draft until unblocked?

**Review by liamsi — APPROVED** [review]
Can be merged after 631 is merged  🙏🏼

**Comment by evan-forbes** [comment]
for some reason, switching from a specific commit to the release tag broke one of the CI tests that compiles the proto files. I can compile the proto files locally fine, so still looking into this

**Comment by evan-forbes** [comment]
created #81 so we can fix the CI later, as the issue is only in CI and this is blocking the rest of the ABCI++ changes

https://github.com/celestiaorg/cosmos-sdk/issues/81

**Pull request merged**
