### PR TITLE
feat: Adds validator qgb checks tests

### PR DESCRIPTION
**Pull request by SweeXordious**
Adds to https://github.com/celestiaorg/cosmos-sdk/issues/114

### CODE REVIEW

**Review by evan-forbes — APPROVED** [review]
mostly simple additions! :+1: utACK

I'm slightly concerned about upgrading a chain to use the QGB module and this change, as we'd either have to pass some address similar to the zero address, or have all of the validators eth address/orchestrator address ahead of time before upgrading.

**Comment by SweeXordious** [comment]
> as we'd either have to pass some address similar to the zero address

You're right. But I thought that we will have some migration script that would change the state that doesn't depend on messages to do state transitions. If it is not, then I should change.

**Comment by evan-forbes** [comment]
Yeah, we can have an upgrade handler do whatever we need without getting that info ahead of time. I'm still worried about it though, at least until we can test upgrade, as having fake addresses as placeholders seems super hacky.

**Comment by evan-forbes** [comment]
nah, let's keep it. After we get mvp working on an integration test, then we'll plan out the upgrade then

**Comment by SweeXordious** [comment]
Merging then?

**Comment by SweeXordious** [comment]
Just renamed the branch we're targeting to: [release/v0.44.x-celestia-qgb](https://github.com/celestiaorg/cosmos-sdk/tree/release/v0.44.x-celestia-qgb). I will make sure it will always have the latest celestia branch changes (hopefuly)

**Comment by evan-forbes** [comment]
sounds good :+1:

**Pull request merged**
