### PR TITLE
chore: Pull v0.45 from upstream

### LINKED ISSUE #42: Pull changes from upstream
pull changes from upstream, specifically for v0.44.5

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description
pull updates from upstream

Closes #42

### CODE REVIEW

**Comment by adlerjohn** [comment]
Can you remove the `:` after closes/fixes/etc? It's preventing the issues from being automatically linked.

**Review by adlerjohn — COMMENTED** [review]
Looks like some directories aren't accessible to the labeler? Can this be fixed?

**Comment by evan-forbes** [comment]
> Looks like some directories aren't accessible to the labeler? Can this be fixed?

looking into this

**Comment by evan-forbes** [comment]
the liveness test fails with the same error running with out any celestia specific changes on release/v0.44.5, so I'm ignoring for now

```
COPY failed: file not found in build context or excluded by .dockerignore: stat db/go.mod: file does not exist
```

not sure why our repo token that is being provided to the labeler can't actually access the repo, perhaps this is some permissions issue?

**Comment by liamsi** [comment]
Why are there so many changes in https://github.com/celestiaorg/cosmos-sdk/pull/43/commits/ec42f98d92a70ce97a2283f95714e3be1655452d ? Were there so many merge conflicts?

**Comment by adlerjohn** [comment]
> not sure why our repo token that is being provided to the labeler can't actually access the repo, perhaps this is some permissions issue?

Because we don't have a `db/` directory.

**Comment by liamsi** [comment]
https://github.com/celestiaorg/cosmos-sdk/blob/master/db/go.mod ?

**Comment by evan-forbes** [comment]
> Why are there so many changes in ec42f98 ? Were there so many merge conflicts?

yeah, I tried rebasing first, but there were a few hundred merge conflicts, so decided to merge instead or sorting through all of them by hand.

> Because we don't have a db/ directory.

should I add it even though the release branch doesn't?

**Comment by evan-forbes** [comment]
If we'd prefer, I'd be happy to create a new branch that starts from v0.44.5, and then add celestia specific changes if that'd be easier to review

**Review by SweeXordious — APPROVED** [review]

**Comment by adlerjohn** [comment]
> https://github.com/celestiaorg/cosmos-sdk/blob/master/db/go.mod ?

https://github.com/celestiaorg/cosmos-sdk/tree/evan/bump-sdk-44.5/db

**Comment by evan-forbes** [comment]
bump :pray: 

if it would make this PR easier to review, I'm happy to start from scratch and introduce the few celestia specific changes rather than pulling updates in from upstream into a pre-existing branch. 

Pretty much the only thing of consequence we modify swapping tendermint for celestia-core, and adding a null method for `PreprocessTxs` to `BaseApp`

as discussed earlier, it looks like the liveness test is failing because of a missing directory. 
```
COPY failed: file not found in build context or excluded by .dockerignore: stat db/go.mod: file does not exist
```

**Pull request closed without merging**
