### PR TITLE
chore: Patch v0.45.1 to support celestia-core

### LINKED ISSUE #42: Pull changes from upstream
pull changes from upstream, specifically for v0.44.5

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

upgrades to v0.45.1, adds the preprocess ABCI method, and replaces tendermint with celestia-core

Closes #42 
unblocks [#186](https://github.com/celestiaorg/celestia-app/pull/186)

### CODE REVIEW

**Comment by evan-forbes** [comment]
liveness test seems to be failing for the same reasons as in #43 https://github.com/celestiaorg/cosmos-sdk/pull/43#issuecomment-1020105248

**Comment by adlerjohn** [comment]
Can the `db` directory requirement be removed, so that CI can pass? Otherwise it will continue to fail forever, no?

https://github.com/celestiaorg/cosmos-sdk/pull/43#issuecomment-1014770620

**Comment by liamsi** [comment]
is this blocked on the lazy shares PR? Should we skip this and go right into 0.46 maybe?

**Comment by evan-forbes** [comment]
we've already upgraded to v0.46, so we can close this

**Pull request closed without merging**
