### PR TITLE
chore: Bump celestia-core to v1.0.0

### PR DESCRIPTION
**Pull request by liamsi**

### CODE REVIEW

**Comment by liamsi** [comment]
Should we bump go in this repo everywhere? https://github.com/celestiaorg/cosmos-sdk/blob/43a5c3e625a2ec7af6a127abd19ad684245bfdee/go.mod#L1

**Comment by adlerjohn** [comment]
Yes

**Comment by liamsi** [comment]
Let's do in a separate PR though. Do you have an idea why 
`Error: buildx failed with: error: failed to solve: process "/bin/sh -c GO111MODULE=on go install   [github.com/golang/protobuf/protoc-gen-go@v${GOLANG_PROTOBUF_VERSION}](http://github.com/golang/protobuf/protoc-gen-go@v$%7BGOLANG_PROTOBUF_VERSION%7D)`

**Comment by liamsi** [comment]
Actually. I think we can delete the proto-builder here. Or we should use our own. The current workflow definitely does not make much sense:
https://github.com/celestiaorg/cosmos-sdk/blob/213921205059175898015513f5b67255780b6ee0/.github/workflows/proto-docker.yml#L39-L44

**Review by adlerjohn — APPROVED** [review]

**Pull request merged**
