### PR TITLE
chore: bump core to 1.1.0

### PR DESCRIPTION
**Pull request by liamsi**
## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by liamsi** [comment]
Meh, `Error: ../../../go/pkg/mod/github.com/celestiaorg/celestia-core@v1.1.0-tm-v0.34.16/types/share_merging.go:8:2: //go:build comment without // +build comment`. Maybe we should just have kept the `// +build` part in rsmt2d. I'll bump to go 1.17 here as well.

**Comment by evan-forbes** [comment]
looks like the liveness test is failing without libleopard

```
Status: Downloaded newer image for cosmossdk/rbuilder:latest
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
rm -rf \
    /tmp/tmp.m7HhfJWrhx/buildsources/build/ \
    artifacts/ \
    tmp-swagger-gen/
Building for linux/amd64
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
mkdir -p /tmp/tmp.m7HhfJWrhx/buildsources/build/
go build -mod=readonly -tags "netgo" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=sim -X github.com/cosmos/cosmos-sdk/version.AppName=simd -X github.com/cosmos/cosmos-sdk/version.Version=74[96](https://github.com/celestiaorg/cosmos-sdk/runs/6072165026?check_suite_focus=true#step:5:96)5660f -X github.com/cosmos/cosmos-sdk/version.Commit=74965660f23ff14e1302232ade0db39cf26cc3eb -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo" -X github.com/tendermint/tendermint/version.TMCoreSemVer=v1.1.0-tm-v0.34.16 -w -s -buildid=74965660f' -trimpath -o /tmp/tmp.m7HhfJWrhx/buildsources/build/ ./...
# github.com/celestiaorg/go-leopard/leopard
/usr/bin/ld: cannot find -llibleopard
/usr/bin/ld: cannot find -llibleopard
/usr/bin/ld: cannot find -llibleopard
/usr/bin/ld: cannot find -llibleopard
```
do we want to fix that before merging? I can look into it a few hours from now if so

**Review by evan-forbes — APPROVED** [review]
#119 

I should have time to dig into #119 later today, so I'm pre-approving

**Comment by liamsi** [comment]
Would be good to fix this before merging but I won't have time to look I to this in the next two days.

**Review by adlerjohn — DISMISSED** [review]

**Comment by liamsi** [comment]
I do not really understand why the liveness tests try to build go-leopard. Everything else worked after switching to go1.17 (which the liveness tests use as well).

**Comment by liamsi** [comment]
actually found the reason: https://hub.docker.com/layers/rbuilder/cosmossdk/rbuilder/latest/images/sha256-0870f37eb666e4c4be9fd22892a32c70247b177008fff06f27b2fb708fe95c34?context=explore

**Comment by liamsi** [comment]
https://github.com/cosmos/cosmos-sdk/issues/10385

**Comment by liamsi** [comment]
> hmm

Just saw that @adlerjohn dismissed his review. The thing I've mentioned above is fixed in 0fa3271.

**Comment by adlerjohn** [comment]
I dismissed my review because CI is still failing

**Comment by liamsi** [comment]
unrelated flaky test which passed before and also on push to master.

**Pull request merged**
