### PR TITLE
chore: Create cosmos-sdk branch that uses Celestia and is based on v.0.44.0 of upstream

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

celestia-app will need a stable version of the sdk to point to, therefore we will also need a stable release branch of the sdk that uses celestia-core instead of tendermint. This PR introduces the minimum changes necessary to do just that.

part of #27

### CODE REVIEW

**Comment by liamsi** [comment]
There has been a patch release btw: https://github.com/cosmos/cosmos-sdk/releases/tag/v0.44.1

**Comment by liamsi** [comment]
Also, I'd like our branches from which we create the releases from to match those with upstream, e.g.: https://github.com/cosmos/cosmos-sdk/tree/release/v0.44.x
The tags (for our releases) should also be the same and additionally, contain a suffix (like previously `-lazy` or sth like that)

That way it is clear where the version we are using originated from, and which version our release is based on. Also, we can pull updates right from the original branch. Same for tendermint. Maybe we should capture this in some markdown file somehow.

**Comment by evan-forbes** [comment]
> Also, I'd like our branches from which we create the releases from to match those with upstream

sounds good! :+1: switched the base of this branch to the latest from upstream v.044.x and also updated this PR branch, so we are now using the patch version along with appropriate naming.

**Review by liamsi — APPROVED** [review]

**Review by tzdybal — APPROVED** [review]
LGTM.

**Pull request merged**
