### PR TITLE
chore: bump tm fork to v1.12.1

### PR DESCRIPTION
**Pull request by cmwaters**

### CODE REVIEW

**Comment by evan-forbes** [comment]
looking into why that test is failing, and then will approve

**Review by evan-forbes — COMMENTED** [review]
whatever is causing the failing test doesn't seem super critical, since all the tests in the app past using the commit in this branch and v1.12.1-tm-v0.34.23, but imho I think it would still be nice to figure out why before moving forward.

wdyt? I'm also ok with opening an issue to investigate and fix later since it does seem like a silly bug, and I don't want to block for that if we're trying to push this through

**Comment by cmwaters** [comment]
It does look as if the previous commit: https://github.com/celestiaorg/cosmos-sdk/commit/7bd9ac2cbdea2e272325a7d71e5c8cb72cf82527 passed this test. I can do a bit of digging.

**Comment by cmwaters** [comment]
This seems to be coming from the `rpc.TxSearch(...)` method in Tendermint. I wonder if it has anything to do with changing the the way hashes are calculated in the kv indexer if they're blobs?

**Comment by cmwaters** [comment]
Ok so I did a somewhat git bisect on the tendermint dependency. It seems the failure happens when we go from v1.4.0-tm-v0.34.20 to v1.5.0-tm-v0.34.20. The most suspicious of these commits are: https://github.com/celestiaorg/celestia-core/commit/534660637ca7f690c994625fd71b57cfe928de19 and https://github.com/celestiaorg/celestia-core/commit/df3814058ebd4343a767111d5975ac7d45807dbd where it looks like we modified how `TxSearch` and `Tx` work in regards to the proof. cc @evan-forbes @rootulp

**Comment by cmwaters** [comment]
Ok I found the problem. It appears to me like everything deadlocks when either `Tx` or `TxSearch` is called with `prove` set to `true`. Setting it to `false` in the SDK makes all the tests pass.

**Review by evan-forbes — APPROVED** [review]
Thanks!! particularly for debugging the broken tx inclusion proofs!

**Pull request merged**
