### PR TITLE
fix: emit status to stdout

### PR DESCRIPTION
**Pull request by rootulp**
Part of https://github.com/celestiaorg/celestia-app/issues/3823

## Testing

After building a celestia-app binary that replaces cosmos-sdk with this, that status output goes to stdout so it can be piped to jq easily. In other words, this works:

```
$ ./build/celestia-appd status | jq .
```

### CODE REVIEW

**Review by rach-id — APPROVED** [review]
utAck

**Review by cmwaters — APPROVED** [review]
utAck. Are there any other areas where we should be using `OutOrStdout` instead of `Println`?

**Comment by julienrbrt** [comment]
If I may (sounds like the same issue Osmosis had), you should probably set the default output in your app instead: https://github.com/cosmos/cosmos-sdk/blob/v0.50.10/simapp/simd/cmd/root.go#L52-L54

`cmd.Println` is just doing its job here: https://pkg.go.dev/github.com/spf13/cobra#Command.Println

The SDK is using `cmd.Println` is more commands.

**Comment by rootulp** [comment]
Thanks for the review @julienrbrt ! Good idea, will do that in celestia-app and close this PR.

**Pull request closed without merging**
