### PR TITLE
fix: signing with Ledger throws an empty error

### LINKED ISSUE #2650: Signing with ledger throws an empty error
### Summary of Bug

When attempting to sign any TX with ledger hardware wallet an empty error is thrown with a second delay. 

```
❯ celestia-appd tx sign tx-test.json --from ledger-test   --chain-id="mocha-4" --offline -s 0 -a 0 --ledger
Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
Error:
```

I tried playing around with various options and flags - the result is always the same

### Version

v1.0.0

### Steps to Reproduce

* Have working ledger and ensure its connected and unlocked
* Add ledger key via `celestia-appd keys add <name> --ledger`
  * This prompts perm on ledger and this works fine
* Generate any test tx with `--generate-only`
* Sign transaction
`celestia-appd tx sign tx-test.json --from <name>  --chain-id="mocha-4" --offline -s 0 -a 0 --ledger`

### For Admin Use

- [X] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by rootulp**
Bumps to ledger-cosmos-go [v.0.13.1](https://github.com/cosmos/ledger-cosmos-go/releases/tag/v0.13.1) to fix https://github.com/celestiaorg/celestia-app/issues/2650. Unblocks https://github.com/celestiaorg/celestia-app/pull/2668

## Notes for reviewers
- Most of the diff in this PR is inspired by https://github.com/cosmos/cosmos-sdk/pull/14661 which hasn't been applied to the v0.46.x branch in cosmos/cosmos-sdk.
- The go.mod changes outside the ledger-cosmos-go bump aren't intentional but they happen automatically via `go mod tidy`

## Testing

Verified this fixes the issue [here](https://github.com/celestiaorg/celestia-app/issues/2650#issuecomment-1759877779)

### CODE REVIEW

**Review by evan-forbes — APPROVED** [review]
nice, thanks for handling this

**Comment by julienrbrt** [comment]
I am late here, but we got Zondax to create https://github.com/cosmos/ledger-cosmos-go/releases/tag/v0.12.3 with the fix as well.
We will bump to that version in mainline v0.46 and v0.47

**Comment by rootulp** [comment]
Thanks for the info! If cosmos/cosmos-sdk v0.46.x gets bumped to ledger-cosmos-go v0.12.3 then we can revert this PR and pull that change into celestiaorg/cosmos-sdk. I'll stay tuned for a cosmos-sdk v0.46.x release with it

**Comment by liamsi** [comment]
https://github.com/cosmos/cosmos-sdk/pull/18112

**Comment by KJ1403** [comment]
I can't open a file I downloaded from assets

**Pull request merged**
