### PR TITLE
chore: add workflow to pull from upstream master

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

This PR introduced a workflow that pulls changes from upstream and the v0.44.x release branch twice a week. 

This PR is blocked by having a github repository secret that is named `PULL_UPSTREAM` that has permissions for repo read and write, along with access to workflows.

we can see this bot in action [on this fork](https://github.com/evan-forbes/cosmos-sdk/pulls)

part of [#528](https://github.com/celestiaorg/celestia-core/issues/528)

### CODE REVIEW

**Comment by liamsi** [comment]
> This PR is blocked by having a github repository secret that is named PULL_UPSTREAM that has permissions for repo read and write, along with access to workflows.

I need to double-check how to do this. I'm fine with giving this the proper perms as long as it can't write to protected branches and has to open PRs like everyone else.

**Comment by evan-forbes** [comment]
see [comment](https://github.com/celestiaorg/celestia-core/pull/558#issuecomment-945012572)

**Comment by evan-forbes** [comment]
This bot would actually be worth it, as we have significantly fewer changes here than in celestia-core, so there shouldn't be many conflicts that require fixing manually. Still leaving as a draft for now, as I won't have time to fix this until January. 

Also, we still need to make a decision as to whether or not we are ok with giving write permissions to a bot.

**Comment by liamsi** [comment]
Thinking about it, we could also just have a bot, that simply opens an issue if there was another SDK release maybe. Just so we will be notified. Same with the core repo. That wouldn't require any extra perms besides opening issues (maybe even a slack bot would be ok otherwise). It would be good if were at least always on par with the latest stable tendermint release and the corresponding SDK.


 I think the main/master branch can just be updated manually on-demand:
image

**Pull request closed without merging**
